input: ../../protocol/Message.fbs
doc:
  schemas: ../../docs/api/schemas
  paths: ../../docs/api/paths.yaml
  tags: ../../docs/api/tags.yaml
output:
  json-schema:
    format: json-schema
    #dir: ../../docs/generated/json-schema
    bundle: ../../docs/generated/json-schema/bundle.json
    base-uri: &base-uri https://motis-project.de/schemas/
    strict-int-types: false
    strict-unions: true
    exclude: &public-exclude
      - motis.import.*
  openapi-3.1:
    format: openapi
    version: 3.1.0
    file: ../../docs/generated/openapi-3.1/openapi.yaml
    base-uri: *base-uri
    ids: false
    info: &openapi-info
      title: MOTIS API
      version: 0.0.0
    exclude: *public-exclude
  openapi-3.0:
    format: openapi
    version: 3.0.3
    file: ../../docs/generated/openapi-3.0/openapi.yaml
    base-uri: *base-uri
    ids: false
    info: *openapi-info
    exclude: *public-exclude
  markdown:
    format: markdown
    dir: ../../docs/generated/markdown
    exclude: *public-exclude
